### ISSUE TITLE
Add GPS point to map for current location

### ISSUE THREAD

**Issue by curtisbarnard** [curtisbarnard/onsenDB#13]
When user allows current GPS location need to plot that location on the map so that user can see their location relative to nearby hot springs.

**Comment by dmitrykulakovfrontend** [comment]
Hello @curtisbarnard

I would like to help with this issue.

**Comment by curtisbarnard** [comment]
@dmitrykulakovfrontend it's been assigned to you. Let me know if you have any questions about how to use leaflet to map points. I don't have any particular styling thought up for the marker that shows your current location so feel free to come up with one yourself. Thanks!
