### ISSUE TITLE
Update HTML metadata

### ISSUE THREAD

**Issue by curtisbarnard** [curtisbarnard/onsenDB#2]
update head with metadata to help with SEO.

**Comment by Khusyasy** [comment]
Hello @curtisbarnard 

I'm interested to help with this issue, can you give me more info about this?

**Comment by curtisbarnard** [comment]
@Khusyasy Sorry It took me so long to get back to you. I think that the page need to have the meta description and tags updated. The site is going to be about finding hot springs and geothermal features around the world so if you can come up with something good to place in those tags it would be great. See the index.html file on lines 6 and 7. Here's a good explanation about using the tags from the MDN: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML#adding_an_author_and_description

I've assigned the issue to you. Please let me know when you think you can have it complete. Thanks!

**Comment by Khusyasy** [comment]
Thanks, @curtisbarnard I'll also take a look at the document that you sent.

Maybe I can take on this issue sometime later today or tomorrow.
